/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBackdrop: typeof import('./src/components/AppBackdrop.vue')['default']
    MeIcon: typeof import('./src/components/MeIcon/MeIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'TheHeader.ce': typeof import('./src/components/TheHeader/TheHeader.ce.vue')['default']
    TheHeaderAvatar: typeof import('./src/components/TheHeader/TheHeaderAvatar.vue')['default']
    TheHeaderAvatarChip: typeof import('./src/components/TheHeader/TheHeaderAvatarChip.vue')['default']
    TheHeaderAvatarMenu: typeof import('./src/components/TheHeader/TheHeaderAvatarMenu.vue')['default']
    TheHeaderAvatarMenuItem: typeof import('./src/components/TheHeader/TheHeaderAvatarMenuItem.vue')['default']
    TheHeaderBrand: typeof import('./src/components/TheHeader/TheHeaderBrand.vue')['default']
    TheHeaderNavigation: typeof import('./src/components/TheHeader/TheHeaderNavigation.vue')['default']
    TheHeaderNavigationItem: typeof import('./src/components/TheHeader/TheHeaderNavigationItem.vue')['default']
    TheHeaderNavigationItemContent: typeof import('./src/components/TheHeader/TheHeaderNavigationItemContent.vue')['default']
    TheHeaderTabs: typeof import('./src/components/TheHeader/TheHeaderTabs.vue')['default']
    TheHeaderTabsNavigationItems: typeof import('./src/components/TheHeader/TheHeaderTabsNavigationItems.vue')['default']
    TheHeaderTabsSiteMapItems: typeof import('./src/components/TheHeader/TheHeaderTabsSiteMapItems.vue')['default']
    UAccordion: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parse_dc66d8436ea295974a3a48a75355c487/node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parse_dc66d8436ea295974a3a48a75355c487/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parse_dc66d8436ea295974a3a48a75355c487/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UChip: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parse_dc66d8436ea295974a3a48a75355c487/node_modules/@nuxt/ui/dist/runtime/components/Chip.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parse_dc66d8436ea295974a3a48a75355c487/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UPopover: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parse_dc66d8436ea295974a3a48a75355c487/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USkeleton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parse_dc66d8436ea295974a3a48a75355c487/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parse_dc66d8436ea295974a3a48a75355c487/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  }
}
